blog/urls.py
from django.conf.urls import url

from blog import views

urlpatterns = [
    url(r'^post/(\d+)', views.post, name="post"),
    url(r'^index', views.index, name="index"),
    url(r'^new_post', views.new_post, name="new_post"),
    url(r'^save_post', views.save_post, name="save_post"),
]

demo/urls.py
from django.conf.urls import url

from demo import views

urlpatterns = [
    url(r'^index/', views.index),
    url(r'^login/', views.login, name="login"),
    url(r'^homepage/', views.home, name="home"),
]

gz1901_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("blog.urls", namespace="blog")),
    url(r'^demo/', include("demo.urls", namespace="demo")),
]

blog/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()

    def __str__(self):
        return self.title

demo/models.py
from django.db import models

# Create your models here.

class Report(models.Model):
    name = models.CharField(max_length=50)
    money = models.PositiveIntegerField()
    get_money = models.PositiveIntegerField(default=300)

    def __str__(self):
        return self.name

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.urls import reverse

from blog.models import Post


def index(request):
    # print(request.path)
    # print(request.method)
    # print(request.GET)
    # print(request.encoding)
    # print(request.COOKIES)
    post_list = Post.objects.all()
    print(post_list)
    context = {"post_list": post_list}
    return render(request, "index.html", context)


def post(request, id):
    post = get_object_or_404(Post, id=id)
    print(post)
    context = {"post": post}
    return render(request, 'detail.html', context)


def new_post(request):
    return render(request, "new_post.html")


def save_post(request):
    title = request.POST.get("title")
    body = request.POST.get("body")
    Post.objects.create(title=title, body=body)
    return HttpResponse("文章保存成功！")


def get_para(request):
    para1 = request.GET.getlist("username")
    para2 = request.GET.get("passwd")
    print(para1, para2)
    return HttpResponse("参数获取成功")


def ret_response(request):
    response = HttpResponse()
    response.content = "Hello Django"
    response.write("I'm fine!")
    response.status_code = 302
    return response


def to_other_url(request):
    return redirect(reverse("blog:post", args=(1,)))

demo/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    context = {"str": "<script>alert('Hi')</script>"}
    return render(request, "demo/home.html", context)


def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        passwd = request.POST.get("passwd")
        request.session['username'] = username
        print(username)
        print(passwd)
        response = HttpResponse("登录成功")
        response.delete_cookie("name")
        return response
    return render(request, "demo/login.html")


def home(request):
    username= request.session.get("username")
    context = {"username": username}
    return render(request, 'homepage.html', context)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Evenの小窝</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
     <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static '' %}">


    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Evenの小窝</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                {% include 'nav.html' %}
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.evenyan.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://www.evenyan.com/">Even的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            {% block main %}
            
            {% endblock %}
        {% block aside %}
        
        {% endblock %}
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.evenyan.com/"
                                                        target="_blank" title="博客模板">我的博客模板</a>
                    - 由<a href="http://www.evenyan.com/" title="博客模板" target="_blank">我的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="js/script.js"></script>

</body>
</html>

templates/demo/home.html
{% extends 'base.html' %}
{% block main %}
    <main class="col-md-8">
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="detail.html">Django 博客开发入门教程：前言</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">Django 博客教程</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                    <span class="post-author"><a href="#">Even</a></span>
                    <span class="comments-link"><a href="#">4 评论</a></span>
                    <span class="views-count"><a href="#">588 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django
                    开发的技巧...</p>
                <div class="read-more cl-effect-14">
                    <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>

        <article class="post post-2">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="detail.html">Django 博客开发入门教程：前言</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">Django 博客教程</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                    <span class="post-author"><a href="#">Even</a></span>
                    <span class="comments-link"><a href="#">4 评论</a></span>
                    <span class="views-count"><a href="#">588 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django
                    开发的技巧...</p>
                <div class="read-more cl-effect-14">
                    <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>


        <!-- 简单分页效果
        <div class="pagination-simple">
            <a href="#">上一页</a>
            <span class="current">第 6 页 / 共 11 页</span>
            <a href="#">下一页</a>
        </div>
        -->
        <div class="pagination">
            <ul>
                <li><a href="">1</a></li>
                <li><a href="">...</a></li>
                <li><a href="">4</a></li>
                <li><a href="">5</a></li>
                <li class="current"><a href="">6</a></li>
                <li><a href="">7</a></li>
                <li><a href="">8</a></li>
                <li><a href="">...</a></li>
                <li><a href="">11</a></li>
            </ul>
        </div>
    </main>
{% endblock %}
{% block aside %}
    <aside class="col-md-4">
        <div class="widget widget-recent-posts">
            <h3 class="widget-title">最新文章</h3>
            <ul>
                <li>
                    <a href="#">Django 博客开发入门教程：前言</a>
                </li>
                <li>
                    <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>
                </li>
                <li>
                    <a href="#">部署 Django 博客</a>
                </li>
            </ul>
        </div>
        <div class="widget widget-archives">
            <h3 class="widget-title">归档</h3>
            <ul>
                <li>
                    <a href="#">2017 年 5 月</a>
                </li>
                <li>
                    <a href="#">2017 年 4 月</a>
                </li>
                <li>
                    <a href="#">2017 年 3 月</a>
                </li>
            </ul>
        </div>

        <div class="widget widget-category">
            <h3 class="widget-title">分类</h3>
            <ul>
                <li>
                    <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>
                </li>
                <li>
                    <a href="#">Python 教程 <span class="post-count">(11)</span></a>
                </li>
                <li>
                    <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>
                </li>
            </ul>
        </div>

        <div class="widget widget-tag-cloud">
            <h3 class="widget-title">标签云</h3>
            <ul>
                <li>
                    <a href="#">Django</a>
                </li>
                <li>
                    <a href="#">Python</a>
                </li>
            </ul>
        </div>
        <div class="rss">
            <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
        </div>
    </aside>
{% endblock %}

templates/demo/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Evenの小窝</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static '' %}">


    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Evenの小窝</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.evenyan.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://www.evenyan.com/">Even的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="detail.html">Django 博客开发入门教程：前言</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">Django 博客教程</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                            <span class="post-author"><a href="#">Even</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django
                            开发的技巧...</p>
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>

                <article class="post post-2">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="detail.html">Django 博客开发入门教程：前言</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">Django 博客教程</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                            <span class="post-author"><a href="#">Even</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django
                            开发的技巧...</p>
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>


                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div>
            </main>
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客开发入门教程：前言</a>
                        </li>
                        <li>
                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>
                        </li>
                        <li>
                            <a href="#">部署 Django 博客</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        <li>
                            <a href="#">2017 年 5 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 4 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 3 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>
                        </li>
                        <li>
                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>
                        </li>
                        <li>
                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.evenyan.com/"
                                                        target="_blank" title="博客模板">我的博客模板</a>
                    - 由<a href="http://www.evenyan.com/" title="博客模板" target="_blank">我的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="js/script.js"></script>

</body>
</html>

templates/demo/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="{% url 'demo:login' %}" method="POST">
    {% csrf_token %}
    用户名： <input type="text" name="username" id=""><br>
    密码： <input type="password" name="passwd" id=""><br>
    <input type="submit" value="提交">
</form>

</body>
</html>

templates/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>文章详情页</title>
</head>
<body>
{{ post.title }}
{{ post.body }}
</body>
</html>

templates/homepage.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>用户中心页</title>
</head>
<body>

{% if username %}
    {{ username }}, 欢迎你。
    {% else %}
    游客，请先<a href="{% url 'demo:login' %}">登录</a>

{% endif %}

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>

欢迎来到我的首页！
<ul>
    {% for post in post_list %}
        <li><a href="{% url 'blog:post' post.id %}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

<a href="{% url 'blog:new_post' %}">写博客</a>

</body>
</html>

templates/nav.html
<nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>

templates/new_post.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>创作博文</title>
</head>
<body>

<form action="{% url 'blog:save_post' %}" method="POST">
    {% csrf_token %}
    文章标题: <input type="text" name="title"><br>
    文章内容: <input type="text" name="body"><br>
    <input type="submit" value="提交文章">

</form>

</body>
</html>